name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: expressme.dev
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
      - name: ğŸ‘¨â€ğŸ’» Project Init & Stop App
        with:
          script: |
            cd /home/project/build
            pm2 stop app
      - name: ğŸ‘¨â€ğŸ’» Remove Previous Project Folder & Clone new master line from Github
        with:
          script: |
            rm -r /home/project/build/Github-Portfolio-Web-Service
            git clone https://github.com/writingdeveloper/Github-Portfolio-Web-Service
      - name: ğŸ‘¨â€ğŸ’» Copy Environment File
        with:
          script: |
            cp .env Github-Portfolio-Web-Service/
            cd Github-Portfolio-Web-Service
      - name: ğŸ‘¨â€ğŸ’» Project Start !
        with:
          script: |
            npm install # install dependencies 
            npm start
